SELECT * FROM PRODUCT ORDER BY LISTPRICE DESC;

SELECT MAX(LISTPRICE) FROM PRODUCT;

-- SELECT COUNT (*) FROM PRODUCT WHERE LISTPRICE = 57.50;

-- SELECT PRODUCT ID, CODE, DESCRIPTION, LISTPRICE
  -- FROM PRODUCT;
  
select PDT.PRODUCTID, PDT.CODE, PDT.DESCRIPTION, PDT.LISTPRICE
  FROM PDT;